[build]
  command = "npm run build"
  publish = "dist"

# (Optional – nur falls du /thank-you.html im /public hast)
[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

# SPA-Fallback für React-Routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
